### ISSUE TITLE
请问如何单独使用缩放功能？

### ISSUE THREAD

**Issue by jayleco** [ibosong/CommentGallery#2]
大神你这个都是带评论的是吧，怎么单独使用缩放功能呢？

**Comment by ibosong** [comment]
单张图，使用ZoomableDraweeView控件。多张图，使用LargeImageGallery控件。

**Comment by jayleco** [comment]
我是之前使用的viewPager+glide实现的滑动和缩放，现在使用老师这个的话我使用viewPager+ZoomableDraweeView控件能直接替换我之前的方案吗？还是必须使用LargeImageGallery来实现多张滑动和缩放？

**Comment by ibosong** [comment]
glide是另一个图片库，ZoomableDraweeView使用的是fresco图片库，两者是冲突的。

**Comment by jayleco** [comment]
我知道，我就是用fresco替换glide来实现

**Comment by ibosong** [comment]
那就直接用LargeImageGallery呗？viewPager+ZoomableDraweeView也是可以的，LargeImageGallery就是它俩的封装

**Comment by jayleco** [comment]
我发现个问题就是老师这个只有一级缩放，PhotoView可以实现2级缩放，也就是双击图片放大到中等大小，再次双击放到最大，老师这个只能双击放到最大，再双击就还原了

**Comment by ibosong** [comment]
是的，这个是官方提供的功能，我也没有再扩展

**Comment by jayleco** [comment]
好的谢谢老师，希望能有更多的Star
